name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '25 4 * * 4'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install ESLint for Frontend
        run: |
          cd frontend
          npm install
          npm install eslint@8.57.0
          npm install @microsoft/eslint-formatter-sarif --save-dev

      - name: Install ESLint for Backend
        run: |
          cd backend
          npm install
          npm install @microsoft/eslint-formatter-sarif --save-dev

      - name: Run ESLint on Frontend
        run: |
          cd frontend
          npx eslint "src/**/*.{js,jsx}" --format @microsoft/eslint-formatter-sarif --output-file ../eslint-frontend-results.sarif
        continue-on-error: true

      - name: Run ESLint on Backend
        run: |
          cd backend
          npx eslint . --ext .js --format @microsoft/eslint-formatter-sarif --output-file ../eslint-backend-results.sarif
        continue-on-error: true

      - name: Upload Frontend analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-frontend-results.sarif
          wait-for-processing: true

      - name: Upload Backend analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-backend-results.sarif
          wait-for-processing: true
